import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export const store = new Vuex.Store({
  state: {
    recipes: [
      {
        id: "1",
        category: "BREAKFAST",
        name: "Crispy Carrot Fries",
        createdBy: "László Barbara",
        image: "Food 1.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "2",
        category: "BREAKFAST",
        name: "Easy Enchilada Sauce",
        createdBy: "László Barbara",
        image: "Food 2.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "3",
        category: "BREAKFAST",
        name: "Thai Edamame Salad",
        createdBy: "László Barbara",
        image: "Food 3.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "4",
        category: "BREAKFAST",
        name: "Nut Butter Snack Bites",
        createdBy: "László Barbara",
        image: "Food 4.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "5",
        category: "BREAKFAST",
        name: "Quinoa and Asparagus",
        createdBy: "László Barbara",
        image: "Food 5.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "6",
        category: "BREAKFAST",
        name: "Mushroom and Kale Pasta",
        createdBy: "László Barbara",
        image: "Food 6.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "7",
        category: "BREAKFAST",
        name: "Crab Cakes",
        createdBy: "László Barbara",
        image: "Food 7.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "8",
        category: "BREAKFAST",
        name: "Gluten free Double Chocolate Chip Brownies",
        createdBy: "László Barbara",
        image: "Food 8.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "9",
        category: "BREAKFAST",
        name: "Crispy Carrot Fries",
        createdBy: "László Barbara",
        image: "Food 9.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "10",
        category: "BREAKFAST",
        name: "Easy Enchilada Sauce",
        createdBy: "László Barbara",
        image: "Food 10.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "11",
        category: "BREAKFAST",
        name: "Thai Edamame Salad",
        createdBy: "László Barbara",
        image: "Food 11.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "12",
        category: "BREAKFAST",
        name: "Nut Butter Snack Bites",
        createdBy: "László Barbara",
        image: "Food 12.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "13",
        category: "BREAKFAST",
        name: "Quinoa and Asparagus",
        createdBy: "László Barbara",
        image: "Food 13.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "14",
        category: "BREAKFAST",
        name: "Mushroom and Kale Pasta",
        createdBy: "László Barbara",
        image: "Food 14.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
      {
        id: "15",
        category: "BREAKFAST",
        name: "Crab Cakes",
        createdBy: "László Barbara",
        image: "Food 15.png",
        createdAt: "",
        preparationTime: 15,
        cookTime: 20,
        ingredients: [
          "4 fresh tomatillos - husked, peeled, and halved",
          "3 Anaheim chile peppers - seeded and halved",
          "3 jalapeno peppers - seeded and halved lengthwise",
          "1 medium onion, halved",
          "1 green bell pepper, seeded and halved lengthwise",
          "2 tablespoons olive oil, divided",
          "salt and ground black pepper to taste",
          "1 ½ pounds pork shoulder, cut into 1-inch chunks",
          "½ (12 fluid ounce) can or bottle lager-style beer",
          "2 tomatoes, chopped",
          "4 cloves garlic, chopped",
          "2 tablespoons chopped fresh oregano",
          "1 tablespoon chopped fresh parsley",
          "1 tablespoon ground cumin",
          "1 teaspoon chili powder",
          "1 beef bouillon cube",
          "4 ounces cream cheese at room temperature",
        ],
        directions: [
          "Preheat the oven to 425 degrees F (220 degrees C).",
          "Arrange the halved tomatillos, Anaheim chiles, jalapeños, onion, and bell pepper on a baking sheet. Drizzle vegetables with 1 tablespoon olive oil and sprinkle with salt.",
          "Roast vegetables in the preheated oven until they begin to show brown spots, about 30 minutes. Allow to cool, then chop vegetables into bite-sized pieces.",
          "Heat remaining 1 tablespoon olive oil in a large skillet over high heat. Add pork and fry until browned, seasoning with salt and black pepper as it cooks, about 12 minutes. Transfer pork to a slow cooker; stir in roasted vegetables. Mix in beer, tomatoes, garlic, oregano, parsley, cumin, chili powder, and bouillon. Cover and cook on Low until pork is tender, 4 to 6 hours.",
          "About 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. Continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. Stir cream cheese mixture back into the chili.",
        ],
        description:
          "Green chili is a Colorado favorite, it's always a crowd pleaser when we have out-of-state visitors. Roasting your veggies first gives this recipe a deeper level of flavor. This can be served over rice as a main course, stuffed in enchiladas, or over potatoes and eggs.",
      },
    ],
  },
  getters: {
    getRecepById: (state) => (id) => {
      return state.recipes.find((recipe) => recipe.id === id);
    },
  },
});
